// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFHlzjUVXzRwYhTDPNXZAs4FlMZQ5xLI',
    appId: '1:1071539468904:web:51ecd0f022a036a8ced9dd',
    messagingSenderId: '1071539468904',
    projectId: 'learningenglishapp-d7f2d',
    authDomain: 'learningenglishapp-d7f2d.firebaseapp.com',
    storageBucket: 'learningenglishapp-d7f2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8cE34OBMGUGOjY986vEbrQ7jsJJA-gM',
    appId: '1:1071539468904:android:d55df22cfe6f61a8ced9dd',
    messagingSenderId: '1071539468904',
    projectId: 'learningenglishapp-d7f2d',
    storageBucket: 'learningenglishapp-d7f2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKl3Rj_zRKEMkBqflXIZ-7IKqzpWmvCJk',
    appId: '1:1071539468904:ios:1d1db7daf5f7e1e2ced9dd',
    messagingSenderId: '1071539468904',
    projectId: 'learningenglishapp-d7f2d',
    storageBucket: 'learningenglishapp-d7f2d.firebasestorage.app',
    iosBundleId: 'com.example.appWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKl3Rj_zRKEMkBqflXIZ-7IKqzpWmvCJk',
    appId: '1:1071539468904:ios:1d1db7daf5f7e1e2ced9dd',
    messagingSenderId: '1071539468904',
    projectId: 'learningenglishapp-d7f2d',
    storageBucket: 'learningenglishapp-d7f2d.firebasestorage.app',
    iosBundleId: 'com.example.appWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeFHlzjUVXzRwYhTDPNXZAs4FlMZQ5xLI',
    appId: '1:1071539468904:web:6e8742151ac1b765ced9dd',
    messagingSenderId: '1071539468904',
    projectId: 'learningenglishapp-d7f2d',
    authDomain: 'learningenglishapp-d7f2d.firebaseapp.com',
    storageBucket: 'learningenglishapp-d7f2d.firebasestorage.app',
  );

}